# Generated by Django 5.0.4 on 2024-06-30 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('letscook', '0006_recipemodel_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercart',
            name='recipies',
            field=models.ManyToManyField(blank=True, null=True, to='letscook.recipemodel'),
        ),
    ]
