# Generated by Django 5.0.4 on 2024-06-14 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letscook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='recipemodel',
            name='steps',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.FloatField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='letscook.ingredientmodel')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='letscook.recipemodel')),
            ],
        ),
    ]
