# Generated by Django 5.0.4 on 2024-06-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letscook', '0002_alter_recipemodel_slug_alter_recipemodel_steps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagmodel',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
