# Generated by Django 5.0.4 on 2024-06-21 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letscook', '0003_tagmodel_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemodel',
            name='video_url',
            field=models.URLField(blank=True, default='https://youtube.com/embed/xvFZjo5PgG0', null=True),
        ),
        migrations.AlterField(
            model_name='tagmodel',
            name='order',
            field=models.IntegerField(default=10),
        ),
    ]
