# Generated by Django 5.0.4 on 2024-06-21 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letscook', '0004_alter_recipemodel_video_url_alter_tagmodel_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemodel',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
