# Generated by Django 5.0.4 on 2024-06-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letscook', '0005_alter_recipemodel_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipemodel',
            name='ingredients',
            field=models.ManyToManyField(through='letscook.RecipeIngredient', to='letscook.ingredientmodel'),
        ),
    ]
