# Generated by Django 5.0.4 on 2024-06-30 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letscook', '0007_ingredientmodel_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientmodel',
            name='group',
            field=models.CharField(choices=[('meat', 'meat'), ('fish', 'fish'), ('vegetables', 'vegetables'), ('spices', 'spices'), ('liquid', 'liquid'), ('sauce', 'sauce'), ('fruits', 'fruits'), ('greenery', 'greenery'), ('all', 'all')], max_length=50),
        ),
    ]
